from __future__ import annotations

import os
import subprocess
import sys
import tarfile
import tomllib
import venv
import zipfile
from email.parser import BytesParser
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def project_version() -> str:
    with (PROJECT_ROOT / "pyproject.toml").open("rb") as metadata:
        return tomllib.load(metadata)["project"]["version"]


SKIPPED_SOURCE_DIRECTORIES = frozenset(
    {"dist", "build", "__pycache__", ".git", ".venv", ".pytest_cache"}
)
PRIVATE_PATH_COMPONENTS = frozenset({"private", "captures", "profiles"})
PROHIBITED_FILENAMES = frozenset(
    {"devices.yaml", "generation-plan.json", "generated-manifest.json"}
)
PROHIBITED_SUFFIXES = (
    ".rec",
    ".bpb",
    ".desc",
    ".proto",
    ".pb",
    "_pb2.py",
    "_pb2.pyi",
    ".jar",
    ".aar",
    ".class",
    ".kt",
    ".swift",
    ".framework",
    ".xcframework",
    ".zip",
)
PROHIBITED_CONTENT_MARKERS = (
    b"Generated by the protocol " + b"buffer compiler",
    b"Copyright (c) Polar " + b"Electro",
    b"Copyright Polar " + b"Electro",
)
PROJECT_OWNED_DECODER_TEMPLATES = frozenset(
    {
        "polar_ble_tools/sdk_tools/decoder_project/DecoderMain.kt",
        "polar_ble_tools/sdk_tools/decoder_project/build.gradle.kts",
        "polar_ble_tools/sdk_tools/decoder_project/settings.gradle.kts",
    }
)


def prohibited_member_reason(member: str) -> str | None:
    """Return the distribution-policy violation for an archive member, if any."""
    normalized = member.replace("\\", "/").lstrip("./")
    parts = tuple(part for part in normalized.split("/") if part)
    names = {part.casefold() for part in parts}
    if "polar-ble-sdk" in names:
        return "SDK checkout"
    if "_generated" in names:
        return "generated schema directory"
    if any(part in names for part in PRIVATE_PATH_COMPONENTS):
        return "private fixture path"
    if Path(normalized).name in PROHIBITED_FILENAMES:
        return "prohibited generated or private file"
    if any(normalized.endswith(template) for template in PROJECT_OWNED_DECODER_TEMPLATES):
        return None
    if normalized.endswith(PROHIBITED_SUFFIXES):
        return "prohibited schema or compiled artifact"
    return None


def source_member_names() -> list[str]:
    completed = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
    )
    members = [name.decode("utf-8") for name in completed.stdout.split(b"\0") if name]
    return [
        name
        for name in members
        if not any(part in SKIPPED_SOURCE_DIRECTORIES for part in Path(name).parts)
    ]


def archive_member_names(artifact: Path) -> list[str]:
    if artifact.suffix == ".whl":
        with zipfile.ZipFile(artifact) as archive:
            return archive.namelist()
    with tarfile.open(artifact) as archive:
        return archive.getnames()


def archive_file_payloads(artifact: Path):
    if artifact.suffix == ".whl":
        with zipfile.ZipFile(artifact) as archive:
            for member in archive.infolist():
                if not member.is_dir():
                    yield member.filename, archive.read(member)
        return
    with tarfile.open(artifact) as archive:
        for member in archive.getmembers():
            if member.isfile():
                extracted = archive.extractfile(member)
                assert extracted is not None
                yield member.name, extracted.read()


def assert_no_prohibited_members(members: list[str]) -> None:
    violations = sorted(
        f"{member}: {reason}"
        for member in members
        if (reason := prohibited_member_reason(member)) is not None
    )
    assert not violations, "Prohibited distribution members:\n" + "\n".join(violations)


def assert_no_prohibited_content(artifact: Path) -> None:
    violations = sorted(
        f"{member}: {marker.decode('ascii')}"
        for member, payload in archive_file_payloads(artifact)
        for marker in PROHIBITED_CONTENT_MARKERS
        if marker.lower() in payload.lower()
    )
    assert not violations, "Prohibited distribution content:\n" + "\n".join(violations)


@pytest.fixture(scope="module")
def built_artifacts(tmp_path_factory: pytest.TempPathFactory) -> list[Path]:
    output_directory = tmp_path_factory.mktemp("artifacts")
    subprocess.run(
        [
            sys.executable,
            "-m",
            "build",
            "--outdir",
            str(output_directory),
        ],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    artifacts = sorted(output_directory.iterdir())
    assert {artifact.suffix for artifact in artifacts} >= {".whl", ".gz"}
    return artifacts


def wheel_metadata(wheel: Path):
    with zipfile.ZipFile(wheel) as archive:
        metadata_name = next(
            name for name in archive.namelist() if name.endswith(".dist-info/METADATA")
        )
        return BytesParser().parsebytes(archive.read(metadata_name))


def wheel_entry_points(wheel: Path) -> str:
    with zipfile.ZipFile(wheel) as archive:
        entry_points_name = next(
            name for name in archive.namelist() if name.endswith(".dist-info/entry_points.txt")
        )
        return archive.read(entry_points_name).decode("utf-8")


def test_prohibited_member_scanner() -> None:
    assert prohibited_member_reason("polar-ble-sdk/protobuf/example.proto") == "SDK checkout"
    assert (
        prohibited_member_reason("polar_ble_tools/_generated/example_pb2.py")
        == "generated schema directory"
    )
    assert (
        prohibited_member_reason("polar_ble_tools/descriptor.desc")
        == "prohibited schema or compiled artifact"
    )
    assert prohibited_member_reason("tests/fixtures/private/device.json") == "private fixture path"
    assert (
        prohibited_member_reason("polar_ble_tools/sdk_tools/decoder_project/DecoderMain.kt") is None
    )
    assert (
        prohibited_member_reason("polar_ble_tools/sdk_tools/decoder_project/untrusted.kt")
        == "prohibited schema or compiled artifact"
    )
    assert prohibited_member_reason("README.md") is None


def test_source_tree_has_no_prohibited_artifacts() -> None:
    assert_no_prohibited_members(source_member_names())


def test_repository_history_audit_is_clean() -> None:
    subprocess.run(
        [sys.executable, "scripts/release_audit.py"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )


def test_wheel_and_sdist_have_no_prohibited_artifacts(built_artifacts: list[Path]) -> None:
    for artifact in built_artifacts:
        assert_no_prohibited_members(archive_member_names(artifact))
        assert_no_prohibited_content(artifact)


def test_wheel_and_sdist_include_project_licence_and_notice(
    built_artifacts: list[Path],
) -> None:
    for artifact in built_artifacts:
        names = {Path(member).name for member in archive_member_names(artifact)}
        assert {"LICENSE", "NOTICE"}.issubset(names)


def test_wheel_metadata_uses_pep_639_and_declares_public_contract(
    built_artifacts: list[Path],
) -> None:
    wheel = next(artifact for artifact in built_artifacts if artifact.suffix == ".whl")
    metadata = wheel_metadata(wheel)

    assert metadata["Name"] == "polar-ble-tools"
    assert metadata["Version"] == project_version()
    assert metadata["Requires-Python"] == ">=3.11"
    assert metadata["License-Expression"] == "Apache-2.0"
    assert {"LICENSE", "NOTICE"}.issubset(metadata.get_all("License-File", []))
    assert set(metadata.get_all("Project-URL", [])) == {
        "Documentation, https://github.com/zyf0717/polar-ble-tools#readme",
        "Issues, https://github.com/zyf0717/polar-ble-tools/issues",
        "Source, https://github.com/zyf0717/polar-ble-tools",
    }
    assert "polar-ble = polar_ble_tools.commands.main:main" in wheel_entry_points(wheel)


def test_distributions_pass_strict_twine_validation(built_artifacts: list[Path]) -> None:
    subprocess.run(
        [
            sys.executable,
            "-m",
            "twine",
            "check",
            "--strict",
            *(str(item) for item in built_artifacts),
        ],
        check=True,
        capture_output=True,
        text=True,
    )


def test_clean_wheel_install_imports_and_shows_help_without_schema_activity(
    built_artifacts: list[Path], tmp_path: Path
) -> None:
    wheel = next(artifact for artifact in built_artifacts if artifact.suffix == ".whl")
    virtual_environment = tmp_path / "clean-venv"
    venv.EnvBuilder(with_pip=True).create(virtual_environment)
    python = virtual_environment / "bin" / "python"
    polar_ble = virtual_environment / "bin" / "polar-ble"
    cache_home = tmp_path / "cache"
    data_home = tmp_path / "data"
    environment = {
        **os.environ,
        "PYTHONNOUSERSITE": "1",
        "XDG_CACHE_HOME": str(cache_home),
        "XDG_DATA_HOME": str(data_home),
    }
    subprocess.run(
        [str(python), "-m", "pip", "install", str(wheel)],
        check=True,
        capture_output=True,
        text=True,
        env={**os.environ, "PYTHONNOUSERSITE": "1"},
    )
    subprocess.run(
        [str(python), "-c", "import polar_ble_tools"],
        check=True,
        capture_output=True,
        text=True,
        env=environment,
    )
    subprocess.run(
        [str(polar_ble), "--version"],
        check=True,
        capture_output=True,
        text=True,
        env=environment,
    )
    for command in ("pair", "connect", "discover", "sdk", "ftu", "raw", "passive", "bpb", "doctor"):
        subprocess.run(
            [str(polar_ble), command, "--help"],
            check=True,
            capture_output=True,
            text=True,
            env=environment,
        )
    assert not (data_home / "polar-ble-tools").exists()
    assert not cache_home.exists()


def test_clean_wheel_sdk_extra_resolves(built_artifacts: list[Path], tmp_path: Path) -> None:
    wheel = next(artifact for artifact in built_artifacts if artifact.suffix == ".whl")
    virtual_environment = tmp_path / "sdk-venv"
    venv.EnvBuilder(with_pip=True).create(virtual_environment)
    python = virtual_environment / "bin" / "python"

    subprocess.run(
        [str(python), "-m", "pip", "install", f"{wheel}[sdk]"],
        check=True,
        capture_output=True,
        text=True,
    )
    subprocess.run(
        [str(python), "-c", "from grpc_tools import protoc; import polar_ble_tools"],
        check=True,
        capture_output=True,
        text=True,
    )
