"""Unofficial local BLE tooling for supported Polar devices."""

from importlib.metadata import version

from polar_ble_tools.api import (
    DeviceDiskSpaceResult,
    DoctorReport,
    DoctorSchemaStatus,
    FtuApplyResult,
    OfflineTriggerResult,
    RawFetchResult,
    RecordingCommandResult,
    RecordingSettingsResult,
    RecordingStatusResult,
    RecordingTypesResult,
    apply_ftu,
    available_recording_types,
    device_disk_space,
    diagnose_ftu,
    doctor,
    fetch_raw_recording,
    ftu_status,
    offline_trigger,
    physical_configuration,
    recording_settings,
    recording_status,
    start_recording,
    stop_recording,
    update_offline_trigger,
    update_user_device_settings,
    user_device_settings,
)
from polar_ble_tools.ble.operations import prepare_device, probe_device, scan_devices
from polar_ble_tools.ble.transport import (
    DeviceLifecycleError,
    DevicePlatform,
    DiscoveredDevice,
    LifecyclePhase,
    LifecycleTimeouts,
    PreparationOutcome,
    PreparationResult,
    ProbeResult,
    ReconnectPersistence,
)
from polar_ble_tools.collection import (
    cleanup_passive_files,
    cleanup_raw_recordings,
    collect_passive_files,
    collect_raw_recordings,
    list_passive_files,
    list_raw_recordings,
)
from polar_ble_tools.device import open_polar_device
from polar_ble_tools.polar.passive import PassiveDomain
from polar_ble_tools.polar.pmd import PmdClient, PolarDeviceDataType

__all__ = [
    "PmdClient",
    "DoctorReport",
    "DoctorSchemaStatus",
    "DeviceDiskSpaceResult",
    "FtuApplyResult",
    "OfflineTriggerResult",
    "PassiveDomain",
    "PolarDeviceDataType",
    "RawFetchResult",
    "RecordingCommandResult",
    "RecordingSettingsResult",
    "RecordingStatusResult",
    "RecordingTypesResult",
    "DeviceLifecycleError",
    "DevicePlatform",
    "DiscoveredDevice",
    "LifecyclePhase",
    "LifecycleTimeouts",
    "PreparationOutcome",
    "PreparationResult",
    "ProbeResult",
    "ReconnectPersistence",
    "open_polar_device",
    "prepare_device",
    "probe_device",
    "scan_devices",
    "apply_ftu",
    "available_recording_types",
    "cleanup_passive_files",
    "cleanup_raw_recordings",
    "collect_passive_files",
    "collect_raw_recordings",
    "diagnose_ftu",
    "device_disk_space",
    "doctor",
    "fetch_raw_recording",
    "ftu_status",
    "list_raw_recordings",
    "list_passive_files",
    "offline_trigger",
    "physical_configuration",
    "recording_settings",
    "recording_status",
    "start_recording",
    "stop_recording",
    "update_offline_trigger",
    "update_user_device_settings",
    "user_device_settings",
    "__version__",
]

__version__ = version("polar-ble-tools")
