"""Unofficial local BLE tooling for supported Polar devices."""

from importlib.metadata import version

from polar_ble_tools.api import (
    DeviceDiskSpaceResult,
    DoctorReport,
    DoctorSchemaStatus,
    FtuApplyResult,
    OfflineTriggerResult,
    RawFetchResult,
    RecordingCommandResult,
    RecordingSettingsResult,
    RecordingStatusResult,
    RecordingTypesResult,
    apply_ftu,
    available_recording_types,
    device_disk_space,
    diagnose_ftu,
    doctor,
    fetch_raw_recording,
    ftu_status,
    offline_trigger,
    physical_configuration,
    recording_settings,
    recording_status,
    start_recording,
    stop_recording,
    update_offline_trigger,
    update_user_device_settings,
    user_device_settings,
)
from polar_ble_tools.ble.bluetoothctl_pairing import (
    PairingError,
    connect_device,
    discover_devices,
    pair_device,
    release_device_connection,
)
from polar_ble_tools.ble.transport import PairingStatus
from polar_ble_tools.collection import (
    cleanup_raw_recordings,
    collect_passive_files,
    collect_raw_recordings,
    list_passive_files,
    list_raw_recordings,
)
from polar_ble_tools.polar.passive import PassiveDomain
from polar_ble_tools.polar.pmd import PmdClient, PolarDeviceDataType

__all__ = [
    "PmdClient",
    "DoctorReport",
    "DoctorSchemaStatus",
    "DeviceDiskSpaceResult",
    "FtuApplyResult",
    "OfflineTriggerResult",
    "PassiveDomain",
    "PolarDeviceDataType",
    "RawFetchResult",
    "RecordingCommandResult",
    "RecordingSettingsResult",
    "RecordingStatusResult",
    "RecordingTypesResult",
    "PairingError",
    "PairingStatus",
    "apply_ftu",
    "available_recording_types",
    "cleanup_raw_recordings",
    "collect_passive_files",
    "collect_raw_recordings",
    "connect_device",
    "diagnose_ftu",
    "device_disk_space",
    "discover_devices",
    "doctor",
    "fetch_raw_recording",
    "ftu_status",
    "list_raw_recordings",
    "list_passive_files",
    "pair_device",
    "offline_trigger",
    "physical_configuration",
    "release_device_connection",
    "recording_settings",
    "recording_status",
    "start_recording",
    "stop_recording",
    "update_offline_trigger",
    "update_user_device_settings",
    "user_device_settings",
    "__version__",
]

__version__ = version("polar-ble-tools")
